version: "2"
run:
  timeout: 5m
linters:
  default: all
  disable:
    - depguard
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - {linters: [cyclop], path: "main\\.go", text: "calculated cyclomatic complexity for function PerformScan"} # Big switch statement. Core logic.
      - {linters: [cyclop], path: "main\\.go", text: "calculated cyclomatic complexity for function main"} # Contains bunch of setup code.
      - {linters: [err113], text: "do not define dynamic errors, use wrapped static errors instead"} # Dynamic errors are fine.
      - {linters: [exhaustruct], text: "cloudwatch\\.PutMetricDataInput is missing fields"} # From library. Not all fields are used.
      - {linters: [exhaustruct], text: "types\\.MetricDatum is missing fields"} # From library. Not all fields are used.
      - {linters: [exhaustruct], text: "v1\\.GetOptions is missing fields"} # From library. Not all fields are used.
      - {linters: [exhaustruct], text: "zerolog\\.ConsoleWriter is missing fields"} # From library. Not all fields are used.
      - {linters: [funlen], path: "main\\.go", text: "Function 'PerformScan' is too long"} # Big switch statement. Core logic.
      - {linters: [funlen], path: "main\\.go", text: "Function 'RunMain' is too long"} # Contains bunch of setup code.
      - {linters: [gochecknoglobals], path: "main\\.go", text: "(program|version|buildDate|gitCommit) is a global variable"} # Global variable is fine.
      - {linters: [perfsprint], text: "fmt\\.Errorf can be replaced with errors\\.New"} # Using fmt.Errorf is fine.
      - {linters: [varnamelen], path: "config\\.go", text: "variable name 'c' is too short for the scope of its usage"} # Stands for config.
      - {linters: [varnamelen], text: "variable name 'i' is too short for the scope of its usage"} # Common name for index.
      - path: .+_test.go
        linters:
          - exhaustruct
          - funlen
          - paralleltest
          - varnamelen
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
