services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github-token
        - homebrew-github-api-token

    command: sleep infinity

    environment:
      - GITHUB_TOKEN
      - MISE_GITHUB_TOKEN
      - HOMEBREW_GITHUB_API_TOKEN
      - RENOVATE_GITHUB_COM_TOKEN

    volumes:
      # Workspace itself.
      - ..:/workspaces/kubestatus2cloudwatch:cached

secrets:
  github-token:
    environment: GITHUB_TOKEN
  homebrew-github-api-token:
    environment: HOMEBREW_GITHUB_API_TOKEN
