# yaml-language-server: $schema=config.schema.json

metric:
  namespace: MyNamespace
  name: MyMetric

targets:
  - kind: StatefulSet
    namespace: observability
    name: prometheus
    mode: AllOfThem
