# yaml-language-server: $schema=https://raw.githubusercontent.com/trallnag/kubestatus2cloudwatch/refs/heads/master/assets/config.schema.json

seconds: 60

metric:
  namespace: MyNamespace
  name: MyMetric

targets:
  - kind: StatefulSet
    namespace: observability
    name: prometheus
    mode: AllOfThem
