name: CI

#
# The primary workflow for continues integration.
#

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - "**"
  schedule:
    # At 04:10 on Monday.
    - cron: 10 4 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  skip:
    name: Skip
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    outputs:
      skip: ${{ steps.skip.outputs.should_skip }}
    steps:
      - id: skip
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          concurrent_skipping: always
          skip_after_successful_duplicate: true

  fix-check:
    needs: skip
    if: needs.skip.outputs.skip != 'true'
    name: Fix & Check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      UV_PYTHON_PREFERENCE: only-system
      UV_PYTHON_DOWNLOADS: never
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0

      # Used by mise to verify tools with aqua backend.
      - name: Set up Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      # Required by golangci-lint.
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: stable
          cache: false

      # Extract subset of mise tools configuration to separate files which are
      # used in subsequent steps as part of cache keys.
      - name: Extract mise tools
        id: extract-mise-tools
        run: |
          mkdir -p tmp

          pipx=tmp/mise-pipx.toml
          gocilint=tmp/mise-gocilint.toml

          echo "pipx=$pipx" | tee -a $GITHUB_OUTPUT
          echo "gocilint=$gocilint" | tee -a $GITHUB_OUTPUT

          grep -F -e pipx mise.toml | tee $pipx
          grep -F -e golangci-lint mise.toml | tee $gocilint

      - name: Set up Python
        id: set-up-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: Set up Astral uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            ${{ steps.extract-mise-tools.outputs.pipx }}

      - name: Cache pre-commit cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pre-commit
          key: >-
            pre-commit cache dir
            ${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Determine current month
        id: determine-current-month
        run: |
          current_month=$(date +%m)
          echo "current-month=$current_month" | tee -a $GITHUB_OUTPUT

      # Caching golangci-lint cache dir by itself is not sufficient. The go
      # build cache is also required. This is handled in the next step.
      - name: Cache golangci-lint cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/golangci-lint
          key: >-
            golangci-lint cache dir
            ${{ steps.determine-current-month.outputs.current-month }}
            ${{ hashFiles(steps.extract-mise-tools.outputs.gocilint) }}

      # Usually the setup-go action will cache the go build cache. But here this
      # behavior is problematic because it clashes with the cache of the test
      # job. The content of the cache is different.
      - name: Cache go build cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/go-build
          key: >-
            go build cache dir
            ${{ steps.determine-current-month.outputs.current-month }}
            ${{ hashFiles(steps.extract-mise-tools.outputs.gocilint) }}

      - name: Set up mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        env:
          MISE_JOBS: 1
          MISE_VERBOSE: 1
        with:
          install: true
          cache: true
          cache_key_prefix: ${{ steps.set-up-python.outputs.python-version }}

      - name: Initialize environment
        run: just init

      - name: Run recipes that fix stuff
        run: just fix

      - name: Run recipes that check stuff
        run: just check

      - name: Commit and push changes
        if: |
          cancelled() == false &&
          github.actor != 'dependabot[bot]' &&
          github.ref_type != 'tag' &&
          startsWith(github.ref, 'refs/head/renovate/') == false
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "ci: Apply automatic improvements"
          commit_options: --no-verify --signoff

  test:
    needs: skip
    if: needs.skip.outputs.skip != 'true'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: just test
